# Generated by Django 4.2.6 on 2023-10-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(max_length=100)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10)),
                ('guest_limit', models.PositiveIntegerField()),
                ('bathroom_count', models.PositiveSmallIntegerField()),
                ('is_pet', models.BooleanField(default=False)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activation_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('num_guests', models.PositiveSmallIntegerField()),
                ('advertisement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immobile.advertisement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='immobile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='immobile.immobile'),
        ),
    ]
